### ISSUE TITLE
mudanças no cáp 6.3 Gerenciamento de Código Fonte

### ISSUE THREAD

**Issue by maiara-pusch** [samuel-rosa/pedologia-quantitativa#1]
**6.3 Gerenciamento de Código Fonte**

O controle de versão é uma prática de fundamental importância para o gerenciamento ao longo do tempo de arquivos em geral, dentre eles arquivos contendo código fonte. Um sistema de controle de versão registra todas as mudança feitas no código fonte. Assim, quando cometemos algum erro ou desenvolvemos o código fonte em uma direção que mais tarde se mostra equivocada, podemos olhar para as versões anteriores do código fonte até encontrarmos o ponto em que erramos ou o momento no qual tomamos aquela direção equivocada. Basta então recuperar aquela versão do código fonte e continuar o seu desenvolvimento dali em diante.
A estratégia de controle de versão mais comumente usada consiste em manter uma estrutura de arquivos mais ou menos com a seguinte:

_meu-novo-projeto/
|- code/
|  |- script01.R
|  |- script01-modificado.R
|  |- script02.R
|  |- script02-revisado.R
|  |- script02-revisado-novo.R
|  |- script-final.R
|  |- script-final-final.R_

Segundo a estratégia acima, cada arquivo é nomeado de acordo com o estágio de desenvolvimento e fazendo uma referência generalista ao tipo de alteração feita. Isso pode ser eficiente quando fazemos poucas alterações ou então alterações pouco significativas. Contudo, à medida que aumenta a complexidade de nosso projeto, maior será o número de edições no código fonte e, também, maior será a complexidade delas. Felizmente existem alternativas bastante mais eficientes do que aquela mostrada acima. Na verdade, um bom sistema de controle de versão dará conta do registro e organização das diferentes versões do código fonte de maneira completamente automática.
Um dos sistemas mais populares de gerenciamento e controle de versão de código fonte é o git. Para facilitar o gerenciamento dos códigos podemos associar o git com nosso repositório do GitHub.

**6.3.1 GitHub**

O GitHub é uma das plataformas mais populares para hospedagem de código fonte, sobretudo entre os usuários e desenvolvedores de pacotes para o R.
Primeiramente, acesse a página do GitHub no endereço abaixo para criar sua conta:
https://github.com/
O login e a senha serão utilizados para vincular seus repositórios do GitHub com o sistema git.

**6.3.2 Git**

Comparado aos outros sistemas de controle de versão, uma das grandes vantagens do git é o fato de ser de fácil instalação e poder ser utilizado localmente, sem necessidade de conexão permanente a um servidor remoto. Isso é possível porque o git realiza todas as operações de gerenciamento do código fonte localmente. Basta submeter (em inglês, commit) ao git toda e qualquer edição importante, associando à ela uma mensagem descritiva. Além da importância para o uso pessoal, essa funcionalidade também é muito importante quando temos acesso limitado ou intermitente ao repositório remoto onde publicamos e compartilhamos o código fonte (por exemplo, por limitada conexão à Internet).
Outra importante funcionalidade do git – comparado aos demais sistemas de controle de versão – é a capacidade de gerenciar diferentes “ramos” (em inglês, branches) de desenvolvimento do código fonte. Assim, há sempre um ramo principal, com a versão mais estável do código fonte, e ramos secundários com os quais podemos fazer testes diversos, tudo isso sem tocar na versão estável do código fonte. Caso os resultados de um ramo de desenvolvimento do código fonte se mostrarem interessantes e julgarmos que vale a pena adicioná-los à versão estável do código fonte, basta fazer a fusão (em inglês, merge) dos dois ramos – ou simplesmente deletar o ramo de teste caso seus resultados se mostrem inúteis. Na prática, isso elimina a necessidade de criação de diferentes arquivos, tanto quando trabalhamos sozinhos, como quando trabalhamos em grupo.
Passemos então à instalação e uso do git!
Para instalar o git em seu computador, vá até o endereço https://git-scm.com/downloads  e descarregue o instalador e estude as diretrizes de instalação para o seu sistema operacional.
Depois de instalado o git, precisamos fazer a sua configuração. Trata-se de informar seu nome e endereço de e-mail para o git. Isso é necessário porque o git registra esses dados à cada edição submetida ao controle de versão. Apesar da pequena utilidade quando trabalhamos sozinhos, essa prática é da maior importância quando duas ou mais pessoas colaboram na edição do código fonte, permitindo identificar quem fez cada alteração. 

6.3.2.1 Configurando o Git
Você só precisa fazer isso uma vez por máquina:

**Configurando com o Git**

Abra o Git bash - Acesse o menu iniciar e procure por Git bash.
Nessa etapa  digitaremos os seguintes comandos:

git config --global user.name “nome do usuário do GitHub”
git config --global user. email  nome@gmail

O endereço de email deve ser o email cadastrado no GitHub

Exemplo:
$ git config --global user.name “Fulano et al”
$ git config -- global user.name fulanoetal@gmail.com

**Configurando com o Rstudio**

Instalar o pacote usethis.
install.packages (“usethis”)
library(usethis)
use_git_config(user.name =”Fulano et al”, user.email= “fulanoetal@gmail.com”)

Após configurarmos o git, a maneira mais fácil de utilizar este sistema para gerenciamento e controle de versão do código fonte - e demais dados e documentos - que produzimos em nossos projetos é via RStudio. Porém, para facilitarmos o gerenciamento dos dados, é sugerido que antes de associarmos o git com o Rstudio, criemos um repositório no GitHub, clonamos este repositório em nosso computador e em seguida criamos um projeto no RStudio.

**Criar um repositório no GitHub**

Clique no simbolo + → New repository. Precisamos adicionar um nome ao repositório (Repository name). Podemos adicionar uma descrição (Description). O diretório pode ser publico ou privado, escolha a melhor opção para seus dados. Em Initialize this repository with: marque as opções: Add a README file e Add.gitignore (em .gitignore template, substitua o NONE  por R) e por último Create repository.

**Clonar o repositório na máquina**

Acesse o repositório criado, e em code copie o endereço HTTPS.
Navegue até o diretório que deseja manter a cópia local do seu respositório. Clique com o botão direito do mouse e selecione Git Bash Here. Irá abrir um promp de comando do Git, nesta janela digitaremos: git clone link HTTPS com o endereço do repositório do GitHub.
 Exemplo  
$ git clone https://github.com/nomeusuario/meu-novo-projeto.git

damos o comando de enter e aparecerá a mensagem abaixo.
Agora, navegue até o diretório e uma pasta com o nome do repositório será criada. Deverá conter a seguinte estrutura mostrada abaixo:

_.git
.gitignore
README.md_

O subdiretório _.git_ consiste no repositório local onde as edições submetidas ao git são registradas.Já o arquivo _.gitignore_ serve para identificar os arquivos e subdiretórios que devem ser, como o próprio nome sugere, ignorados pelo git. É o caso, por exemplo, de um subdiretório temporário criado para armazenar produtos do projeto que podem mudar a cada instante e serem descartados a qualquer momento.

**Criar um projeto no RStudio**

Agora precisamos criar um projeto no RStudio e associar a pasta onde o repositório do GitHub foi clonado. (Files > New Project > Existing Directory > Browse (seleciona a pasta clonada) > Create Project).

Deverá ser adicionado a pasta duas novas estruturas:
_.Rproj.user
meu-novo-projeto.Rproj_

Tando o subdiretório _.Rproj.user_ como o arquivo _meu-novo-projeto.Rproj_ já foram descritos anteriormente. 

Caso as estuturas não apareçam, pode ser preciso habilitar a visualização de arquivos ocultos em seu gerenciador de arquivos 😉.

**Adicionar dados ao repositório**

Uma sugestão e manter a estrutura de organização apresenta na introdução deste capitulo. Podemos adicionar arquivos na pasta associada ao GitHub e fazer upload dos arquivos via Rstudio. Abra o projeto do RStudio criado, e note que agora temos uma aba no painel Environment chamada Git. Nesta aba irá aparecer os arquivos que podemos fazer upload para o respositório. Precisamos selecionar o arquivo, marcando a opção Staged. No status irá aparecer a letra A. Agora clique em commit, nesta etapa podemos selecionar os arquivos que desejamos manter na pasta, porém não queremos fazer upload para o repositório. Para isso, clique com o botão direito  do mouse sobre o nome do arquivo e seleciona a opção Ignore. Após selecionar os arquivos, podemos adicionar comentário (Commit message) sobre as alterações que foram realizadas, e  clicamos em commit. Por fim, clicamos em push  e finalizamos o envio dos arquivos ao repositório do GitHub.

**Comment by samuel-rosa** [comment]
@maiara-pusch obrigado pelas contribuições. Note que este espaço serve para discussão. Caso queira fazer contribuições ao documento, tu precisa:

* fazer um `fork` do repositório para tua conta,
* incluir as alterações que julgar necessárias,
* submeter as alterações na forma de `pull request`.
